# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalendarDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'FSCalendar'

  # Pods for CalendarDemo

  target 'CalendarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalendarDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
