# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopDetailDescription' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Kingfisher'
    pod 'SDCycleScrollView','>= 1.80'
    pod 'SnapKit', '~> 5.0.0'


  # Pods for ShopDetailDescription

  target 'ShopDetailDescriptionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopDetailDescriptionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
