# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.0.0-rc.2'
    pod 'RxCocoa', '6.0.0-rc.2'
    pod 'SnapKit'
    pod 'HandyJSON', '~> 5.0.2'
    pod 'TextFieldEffects'
    pod 'Kingfisher', '~> 5.0'

  # Pods for Rx

end
